#!/bin/sh

NAME=`basename $0`

function Usage()
{
    echo "Usage: ${NAME} <application>"
    exit 1
}

if [ $# -lt 1 ]; then
    Usage
fi

CHECK_GPU=""
COMMAND=""

if [[ ${CHECK_GPU} == "" ]]; then
    module load mesalib
else
    module load virtualgl 
    COMMAND=$(which vglrun)
fi

${COMMAND} "$@"
