#!/bin/sh

SOURCE_DIR=$1
BUILD_DIR=$2
INSTALL_DIR=$3

RESOURCE_DIR="${SOURCE_DIR}/resource"
VERSION=`echo ${SOURCE_DIR} | awk -F/ '{print $NF}'`
BIN="${INSTALL_DIR}/bin"
CVL="${INSTALL_DIR}/share/cvl"

if [ ! -d "${RESOURCE_DIR}" ]; then
    echo "Error ${RESOURCE_DIR} does not exist"
    exit 1
fi

MODULES=`find ${INSTALL_DIR}/share/* -name Modules`
cp -f ${RESOURCE_DIR}/*.cmake ${MODULES}

if [ ! -d "${CVL}" ]; then
    mkdir "${CVL}"
fi

cp -f ${RESOURCE_DIR}/Module_CMakeLists.txt ${CVL}
cp -f ${RESOURCE_DIR}/Root_CMakeLists.txt ${CVL}
cp -f ${RESOURCE_DIR}/Version_CMakeLists.txt ${CVL}
cp -f ${RESOURCE_DIR}/check ${CVL}
cp -f ${RESOURCE_DIR}/config ${CVL}
cp -f ${RESOURCE_DIR}/test1 ${CVL}
cp -f ${RESOURCE_DIR}/readme.txt ${CVL}
cp -f ${RESOURCE_DIR}/validate_module.sh ${CVL}

cp -f ${RESOURCE_DIR}/ccreate ${BIN}

# Copy module validation script to package directory.
if [ ! -f ${INSTALL_DIR}/validate_module.sh ]; then
    cp ${SOURCE_DIR}/validate_module.sh ${INSTALL_DIR}
fi
