set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${${PROJECT_NAME}_DESCRIPTION_SUMMARY})
set(CPACK_PACKAGE_VENDOR "${${PROJECT_NAME}_PACKAGE_VENDOR}")
set(CPACK_PACKAGE_VERSION "${${PROJECT_NAME}_VERSION}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME} ${${PROJECT_NAME}_VERSION}")
set(CPACK_PACKAGE_NAME ${${PROJECT_NAME}_CPACK_PACKAGE_NAME})
set(CPACK_PACKAGE_VERSION_MAJOR "${${PROJECT_NAME}_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${${PROJECT_NAME}_VERSION_MINOR}")
set(CPACK_RPM_PACKAGE_RELEASE "${${PROJECT_NAME}_PACKAGE_RELEASE}")

if(NOT CvlEnableComponentPackage)
    set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_RPM_PACKAGE_RELEASE}.${CPACK_SYSTEM_NAME}")
endif()

set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME} ${${PROJECT_NAME}_VERSION}")

if(${PROJECT_NAME}_PRE_SCRIPT_FILE)
    set(CPACK_RPM_PRE_INSTALL_SCRIPT_FILE "${${PROJECT_NAME}_PRE_SCRIPT_FILE}")
endif()

if(${PROJECT_NAME}_POST_SCRIPT_FILE)
    set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "${${PROJECT_NAME}_POST_SCRIPT_FILE}")
endif()

if(${PROJECT_NAME}_RPM_PACKAGE_REQUIRES)
    set(CPACK_RPM_PACKAGE_REQUIRES "${${PROJECT_NAME}_RPM_PACKAGE_REQUIRES}")
endif()

if(${PROJECT_NAME}_DEPENDENCY_CHECK STREQUAL "false")
    set(CPACK_RPM_SPEC_MORE_DEFINE "%define __find_requires %{nil}\n%define __find_provides %{nil}\nAutoreqprov: no\nAutoprov: no\nAutoreq: no")
endif()

include(CPack)
