#!/bin/sh

NAME=`basename $0`

function Usage()
{
    echo "Usage: ${NAME} <application>"
    exit 1
}

if [ $# -lt 7 ]; then
    Usage
fi

APPLICATION=$1
CHECK_GPU=""
COMMAND=""

if [[ ${CHECK_GPU} == "" ]]; then
    module load mesalib
else
    module load virtualgl 
    COMMAND="vglrun"
fi

${COMMAND} ${APPLICATION}
