#!/bin/sh

ARG0=`basename $0`
Geometry="1440x900"
Depth="24"
DefaultDisplay="1"
#Display="${DefaultDisplay}"
VncServer="tigervnc"
MODULE=`echo $MODULEPATH`

if [ -z "${MODULE}" ]; then
    source /etc/profile.d/modules.sh    
fi

if [ ! -d "/usr/local/tigervnc" ]; then
    VncServer="turbovnc"
fi

module load libjpeg-turbo
#module load turbovnc

function Usage()
{
    echo "Usage: "
    echo "${ARG0} - Start VNC session using default configuration."
    echo "${ARG0} --geometry <geometry_value> --display <display_number> --vnc <tigervnc|turbovnc> - Start VNC session using user configuration"
    echo "${ARG0} stop <display_number> - Stop VNC session"
}

function SetVnc()
{
    vnc=$1

    if [ "${vnc}" == "tigervnc" ]; then 
        if [ -d "/usr/local/tigervnc" ]; then
            VncServer=${vnc}
        else
            echo "Error: tigervnc is not installed"
        fi
    elif [ "${vnc}" == "turbovnc" ]; then
        VncServer=${vnc}
    else
        echo "Error: ${vnc} is not a valid name"
    fi
}

function List()
{
    module load ${VncServer}

    vncserver -list
}

function Stop()
{
    module load ${VncServer}

    if [ -z ${Display} ]; then
        Display="${DefaultDisplay}"
    fi

    vncserver -kill :${Display}
}

function Start()
{
    if [ -z "${Display}" ]; then
        vncserver -geometry ${Geometry} -depth ${Depth}
    else
        vncserver -geometry ${Geometry} -depth ${Depth} :${Display}
    fi
}

function Initialisation()
{
    if [ ! -d ${HOME}/.config/xfce4 ]; then
        mkdir -p ${HOME}/.config/xfce4
    fi

    CONFIG_PREFIX=`which vncserver | sed "s/\/bin\/vncserver//g"`
    CONFIG_LIB="${CONFIG_PREFIX}/config"

    if [ ! -d ${HOME}/.config/xfce4/xfconf ]; then
        cp -r ${CONFIG_LIB}/xfce4 ${HOME}/.config
    fi

    if [ ${VncServer}="tigervnc" ]; then
        if [ ! -d ${HOME}/.vnc ]; then
            mkdir ${HOME}/.vnc
        fi
        if [ ! -f ${HOME}/.vnc/xstartup ]; then
            cp ${CONFIG_LIB}/xstartup ${HOME}/.vnc
        fi
    fi
}

while [ $# -ge 1 ]; do
    case "$1" in
        -d|--display)
            Display=$2
            ;;
        -g|--geometry)
            Geometry=$2
            ;;
        -h|--help)
            Usage
            exit 0
            ;;
        -l|--list)
            List
            exit 0
            ;;
        -s|stop)
            Display=$2
            Stop
            exit 0
            ;;
        -v|--vnc)
            SetVnc $2
            ;;
    esac
    shift
done

module load ${VncServer} 
Initialisation
Start
