#!/bin/sh
#
# CVL build system to check or configure building process after installation.
#

SOURCE_DIR=$1
BUILD_DIR=$2
INSTALL_DIR=$3

cp -R /usr/share/xorg-x11-server-source/* ${BUILD_DIR}/unix/xserver/
cd ${BUILD_DIR}/unix/xserver/
patch -p1 < ../xserver110.patch
autoreconf -fiv
./configure --with-pic --without-dtrace --disable-static --disable-dri --disable-xinerama --disable-xvfb --disable-xnest --disable-xorg --disable-dmx --disable-xwin --disable-xephyr --disable-kdrive --disable-config-dbus --disable-config-hal --disable-config-udev --disable-dri2 --enable-install-libxf86config --enable-glx --with-default-font-path="catalogue:/etc/X11/fontpath.d,built-ins" --with-xkb-path=/usr/share/X11/xkb --with-xkb-output=/var/lib/xkb --with-xkb-bin-directory=/usr/bin --with-serverconfig-path=/usr/lib64/xorg
cp -f ${SOURCE_DIR}/Makefile hw/vnc
make TIGERVNC_SRCDIR=../..
cp hw/vnc/Xvnc ${INSTALL_DIR}/bin

# Todo: move following implementation to CVL system installation.
if [ ! -d "${INSTALL_DIR}/config" ]; then
    mkdir ${INSTALL_DIR}/config
fi

cp -fr ${SOURCE_DIR}/xfce4 ${INSTALL_DIR}/config
cp -f ${SOURCE_DIR}/xstartup ${INSTALL_DIR}/config

# Copy module validation script to package directory.
if [ ! -f ${INSTALL_DIR}/validate_module.sh ]; then
    cp ${SOURCE_DIR}/validate_module.sh ${INSTALL_DIR}
fi
