#!/bin/sh

PROGRAM=`basename $0`

function Usage()
{
    echo "Usage: ${PROGRAM} <license file>"
    exit 1
}

if [ $# -lt 1 ]; then
    Usage
fi

LICENSE=$1

INSTALLER="cvl-license-installer.sh"

module load cvl

CvlCreateLicenseInstaller.py --license ${LICENSE} --script  ${INSTALLER}
